name: DanielGarza
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#afd4ff'
    - '#111514'
    - '#474745'
    - '#96a15d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
