name: DanielGarza
favicon: null
layout_spectrum: 0.52063311310485
typography_spectrum: 0.07366216857917607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.12801268487237394
  lightness: 0.9681146419607103
  saturation: 0.042839756002649665
  rhythmicContrast: 0.516868551960215
purpose: []
